[package]
name = "uot-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
bytes = "1"
thiserror = "1"
tracing = "0.1" # For logging
tokio-util = { version = "0.7", features = ["codec"] }